---
title: "RAM Book"
author: "Martín Vargas Estrada"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Estructura


```{r cars, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(tidyverse)
library(haven)
INDI45 <- read_sav("INDI45.sav")
# glimpse(INDI45)
ayudin <- function(dataframe, columnas) {
  # Verificar que las columnas seleccionadas sean numéricas
  if (!all(sapply(columnas, function(col) is.numeric(dataframe[[col]])))) {
    stop("Todas las columnas seleccionadas deben ser numéricas.")
  }
  
  # Filtrar el dataframe eliminando filas con NA en las columnas seleccionadas
  dataframe_limpio <- dataframe[complete.cases(dataframe[, columnas]), columnas]
  
  # Devolver el dataframe limpio
  return(dataframe_limpio)
}

# Ejemplo de uso:
# df_limpio <- limpiar_dataframe(dataframe = mi_dataframe, columnas = c(2, 4, 6))


# Llamar a la función y mostrar los resultados
LIMPION <- ayudin(dataframe = INDI45, columnas = c(44:105))
```



```{r CHECKING, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, results='asis'}
# Carga el archivo .sav

# Función para generar un listado detallado de las variables de un df
# Supongamos que 'df' es tu dataframe
ojeada <- function(df) {
  data.frame(
    No._Col = seq_along(names(df)),
    Nombre_Var = names(df),
    Tipo_Var = sapply(df, function(x) paste(class(x), collapse = ", ")),
    Contenido = sapply(df, function(x) {
      if (is.factor(x)) {
        # Para factores, muestra los niveles
        paste(levels(x)[head(as.integer(x), 3)], collapse = ", ")
      } else if (is.list(x)) {
        # Para listas, indica el tipo y la longitud
        paste("List of", length(x))
      } else {
        # Para otros tipos, muestra los primeros 3 valores
        paste(head(x, 3), collapse = ", ")
      }
    }),
    stringsAsFactors = FALSE
  )
}


variable_info <- ojeada(PULCRO)
# print(variable_info)
library(knitr) # Para usar kable

# Formato con kable
kable(variable_info, format = "markdown")
```

